name: '${project_name}'
author: SuperPenguin
version: '${version}'
main: com.github.mlgpenguin.plugintemplate.PluginTemplate
api-version: '1.20'
description: A Kotlin Plugin Template!
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.9.0"
