name: '${project_name}'
author: SuperPenguin
version: '${version}'
main: com.github.mlgpenguin.moneytokens.MoneyTokens
api-version: '1.20'
description: Very LightWeight plugin allows creating Redeemable Money Tokens
softdepend: [Vault]
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.9.0"
